name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Config registry
        run: npm set registry file://./cache/module_cache/storage

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
