name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Download npm cache from cache branch if cache miss
        continue-on-error: true
        run: |
          echo "Downloading npm cache from cache branch"
          git fetch origin cache-branch
          git checkout origin/cache-branch -- .npm/cache

      - name: Install dependencies
        run: npm install --cache .npm/cache --no-audit --no-fund

      - name: Run tests
        run: npm test

      - name: Commit and push npm cache to cache branch if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/cache-branch; then
            echo "cache-branch exists"
            git checkout cache-branch
            git pull origin cache-branch
            git add .npm/cache
          else
            echo "cache-branch does not exist, creating it"
            git checkout -b cache-branch
            git rm -rf .
            git add .npm/cache
          fi
          if ! git diff-index --quiet HEAD; then
            LAST_COMMIT_MSG=$(git log -1 --pretty=%B origin/main)
            git commit -m "$LAST_COMMIT_MSG"
            git push origin cache-branch --force
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
