name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Start Verdaccio
        run: npx verdaccio --config ./module_cache/config.yaml &

      - name: Wait for Verdaccio to start
        run: sleep 30

      - name: Configure npm to use Verdaccio
        run: npm set registry http://localhost:4873/

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
