name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Cache npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: .npm/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Download npm cache artifact if cache miss
        if: steps.cache-npm.outputs.cache-hit != 'true'
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: npm-cache
          path: .npm/cache

      - name: Install dependencies
        run: npm install --cache .npm/cache

      - name: Save npm cache as artifact
        if: steps.cache-npm.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: npm-cache
          path: .npm/cache

      - name: Run tests
        run: npm test
