name: workflow_deploy

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get OIDC token
        run: |
          echo "${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}" 
          echo "${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}"
          curl -sSL -H "Authorization: bearer ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}" "${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}"